openapi: 3.0.3
info:
  title: MyMoolah API
  version: 1.0.0
  description: |
    RESTful API for the MyMoolah banking and wallet platform.
servers:
  - url: https://api.mymoolah.com
paths:
  /api/users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input
  /api/clients:
    get:
      summary: List all registered B2B clients
      responses:
        '200':
          description: A list of clients
